import { NextResponse } from 'next/server';
import { writeFileSync, mkdirSync, existsSync, readdirSync, readFileSync } from 'fs';
import path from 'path';
import os from 'os';

// Resolve paths consistently: .data lives inside the dashboard project root.
const ROOT_DIR = process.cwd();
const DATA_DIR = path.join(ROOT_DIR, '.data');
const IDENTITIES_DIR = path.join(DATA_DIR, 'identities');
const RETIRED_DIR = path.join(DATA_DIR, 'retired_identities');
const COMPANIES_FILE = path.join(DATA_DIR, 'companies.json');

if (!existsSync(IDENTITIES_DIR)) mkdirSync(IDENTITIES_DIR, { recursive: true });
if (!existsSync(RETIRED_DIR)) mkdirSync(RETIRED_DIR, { recursive: true });

export async function GET() {
  try {
    const parseIdentities = (dir) => {
      if (!existsSync(dir)) return [];
      const files = readdirSync(dir).filter(f => f.endsWith('.env') && !f.startsWith('_'));
      return files.map(f => {
        const text = readFileSync(path.join(dir, f), 'utf8');
        const env = {};
        text.split('\n').forEach(line => {
          const match = line.trim().match(/^export\s+([A-Z0-9_]+)=(.*)$/);
          if (match) env[match[1]] = match[2].replace(/"/g, '');
        });
        return {
          filename: f,
          role: env.RUNNER_ROLE || f.replace('.env', ''),
          agentId: env.PAPERCLIP_AGENT_ID || '',
          apiUrl: env.PAPERCLIP_API_URL || '',
          companyId: env.PAPERCLIP_COMPANY_ID || '',
          executor: env.RUNNER_EXECUTOR || 'claude',
          model: env.RUNNER_MODEL || '',
          timeoutMs: parseInt(env.RUNNER_TIMEOUT_MS) || 1800000,
        };
      });
    };

    return NextResponse.json({ 
      success: true, 
      identities: parseIdentities(IDENTITIES_DIR),
      retiredIdentities: parseIdentities(RETIRED_DIR)
    });
  } catch (error) {
    return NextResponse.json({ success: false, error: String(error) }, { status: 500 });
  }
}

export async function POST(req) {
  try {
    const body = await req.json();
    const { companyId, roleName, executor } = body;

    if (!companyId || !roleName) {
      return NextResponse.json({ success: false, error: "Missing required fields (companyId, roleName) for Auto-Join." }, { status: 400 });
    }

    if (!existsSync(COMPANIES_FILE)) {
      return NextResponse.json({ success: false, error: "No companies vault found. Please configure a company first." }, { status: 400 });
    }
    
    const companies = JSON.parse(readFileSync(COMPANIES_FILE, 'utf8'));
    const company = companies.find(c => c.id === companyId);
    if (!company) {
      return NextResponse.json({ success: false, error: `Company ${companyId} not found in local vault.` }, { status: 404 });
    }

    const { apiUrl: url, boardKey } = company;

    // 1. Create Agent on the remote cloud server
    const createRes = await fetch(`${url}/api/companies/${companyId}/agents`, {
      method: "POST",
      headers: { "Authorization": `Bearer ${boardKey}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        name: `Matrix Node ${roleName} (${os.hostname()})`,
        role: roleName,
        adapter_type: "process",
        adapter_config: { executor: executor || "claude" }
      })
    });

    if (!createRes.ok) throw new Error(`Agent creation failed HTTP ${createRes.status}`);
    const agent = await createRes.json();

    // 2. Obtain API Key from remote
    const keyRes = await fetch(`${url}/api/agents/${agent.id}/keys`, {
      method: "POST",
      headers: { "Authorization": `Bearer ${boardKey}`, "Content-Type": "application/json" },
      body: JSON.stringify({ name: "matrix-auto-key" })
    });

    if (!keyRes.ok) throw new Error(`Key creation failed HTTP ${keyRes.status}`);
    const keyData = await keyRes.json();
    const apiKey = keyData.key || keyData.apiKey || keyData.plaintextKey || keyData.token;

    // 3. Write locally to identities vault
    const timeoutMs = 1800000;
    const envContent = [
      `# ATOMIC IDENTITY FILE GENERATED BY MATRIX DASHBOARD`,
      `export PAPERCLIP_API_URL="${url}"`,
      `export PAPERCLIP_COMPANY_ID="${companyId}"`,
      `export PAPERCLIP_AGENT_ID="${agent.id}"`,
      `export PAPERCLIP_API_KEY="${apiKey}"`,
      `export RUNNER_EXECUTOR="${executor || 'claude'}"`,
      `export RUNNER_TIMEOUT_MS="${timeoutMs}"`,
      `export RUNNER_ROLE="${roleName}"`,
    ].join("\n");

    const envPath = path.join(IDENTITIES_DIR, `${roleName}.env`);
    writeFileSync(envPath, envContent, "utf8");

    return NextResponse.json({ success: true, agentId: agent.id, role: roleName });

  } catch (error) {
    return NextResponse.json({ success: false, error: String(error) }, { status: 500 });
  }
}

export async function PATCH(req) {
  try {
    const { role, executor, model } = await req.json();
    if (!role) {
      return NextResponse.json({ success: false, error: "Role is required." }, { status: 400 });
    }

    const envPath = path.join(IDENTITIES_DIR, `${role}.env`);
    if (!existsSync(envPath)) {
      return NextResponse.json({ success: false, error: `Identity ${role} not found.` }, { status: 404 });
    }

    let text = readFileSync(envPath, 'utf8');

    // Replace or append RUNNER_EXECUTOR
    if (executor) {
      if (text.match(/^export RUNNER_EXECUTOR=/m)) {
        text = text.replace(/^export RUNNER_EXECUTOR=.*$/m, `export RUNNER_EXECUTOR="${executor}"`);
      } else {
        text += `\nexport RUNNER_EXECUTOR="${executor}"`;
      }
    }

    // Replace or append RUNNER_MODEL
    if (model) {
      if (text.match(/^export RUNNER_MODEL=/m)) {
        text = text.replace(/^export RUNNER_MODEL=.*$/m, `export RUNNER_MODEL="${model}"`);
      } else {
        text += `\nexport RUNNER_MODEL="${model}"`;
      }
    }

    writeFileSync(envPath, text, 'utf8');
    return NextResponse.json({ success: true, message: `Updated ${role}: executor=${executor}, model=${model}` });
  } catch (error) {
    return NextResponse.json({ success: false, error: String(error) }, { status: 500 });
  }
}

export async function DELETE(req) {
  // [HOTFIX] Forcing Next.js Turbopack invalidation tick 
  try {
    const { role } = await req.json();
    if (!role) return NextResponse.json({ success: false, error: "Role missing." }, { status: 400 });

    const activeFile = path.join(IDENTITIES_DIR, `${role}.env`);
    const retiredFile = path.join(RETIRED_DIR, `${role}.env`);

    if (!existsSync(activeFile)) {
      return NextResponse.json({ success: false, error: `Agent ${role} is not an active node.` }, { status: 404 });
    }

    // Physical File Move
    const fileData = readFileSync(activeFile, 'utf8');
    writeFileSync(retiredFile, fileData, 'utf8');
    require('fs').unlinkSync(activeFile);

    return NextResponse.json({ success: true, message: `Node ${role} successfully retired and archived.` });
  } catch (error) {
    return NextResponse.json({ success: false, error: String(error) }, { status: 500 });
  }
}
